# Generated by Django 3.2.9 on 2021-12-14 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20211206_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_media',
            name='session_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='date_modified',
            field=models.CharField(default=datetime.date(2021, 12, 14), max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='end_date',
            field=models.CharField(default=datetime.date(2021, 12, 14), max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='start_date',
            field=models.CharField(default=datetime.date(2021, 12, 14), max_length=50),
        ),
    ]
