# Generated by Django 3.2.9 on 2021-12-16 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_registermodel_auth_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionmodel',
            old_name='host_user_email',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='date_modified',
            field=models.CharField(default=datetime.date(2021, 12, 16), max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='end_date',
            field=models.CharField(default=datetime.date(2021, 12, 16), max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='start_date',
            field=models.CharField(default=datetime.date(2021, 12, 16), max_length=50),
        ),
    ]
