# Generated by Django 3.2.9 on 2021-12-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=128)),
                ('content_name', models.CharField(max_length=128)),
                ('content_type', models.CharField(max_length=128)),
                ('thumbnail_path', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=128)),
                ('access_type', models.CharField(max_length=128)),
                ('file_path', models.CharField(max_length=300)),
                ('file_name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=300)),
                ('buildtarget', models.CharField(max_length=200)),
            ],
        ),
    ]
