# Generated by Django 3.2.9 on 2021-12-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='content_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
