# Generated by Django 3.2.9 on 2021-12-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contentmodel_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='content_id',
            field=models.CharField(max_length=128),
        ),
    ]
