# Generated by Django 3.2.9 on 2021-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_contentmodel_content_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=128)),
                ('contnet_name', models.CharField(max_length=128)),
                ('content_type', models.CharField(max_length=128)),
                ('content_load_type', models.CharField(max_length=150)),
                ('thumbnail_path', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=200)),
                ('access_type', models.CharField(max_length=128)),
                ('path', models.FilePathField()),
                ('version', models.CharField(max_length=128)),
                ('file_name', models.CharField(max_length=128)),
                ('build_target', models.CharField(max_length=128)),
            ],
        ),
    ]
