# Generated by Django 3.2.9 on 2021-12-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_usercontentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontentmodel',
            name='contnet_name',
            field=models.CharField(max_length=528),
        ),
    ]
