# Generated by Django 3.2.9 on 2021-12-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_usercontentmodel_contnet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontentmodel',
            old_name='contnet_name',
            new_name='content_name',
        ),
    ]
